# .github/FUNDING.yml
# This adds a "Sponsor" button to the right sidebar of your GitHub repo
custom:
 # - https://github.com/Svarkovsky/s3-msx-pc/blob/master/DONATE.md

  - https://svarkovsky.github.io/donate
  
