// SPDX-License-Identifier: GPL-3.0-or-later

static const char webui_html[] = {
"<!DOCTYPE html>"
"<html>"
"<head>"
"<meta name='viewport' content='width=device-width, initial-scale=1'>"
"<title>S3-MSX-PC Web Interface</title>"
"<style>"
"    body {max-width:960px;margin:0 auto;padding:1.5em;font-family:monospace;color:#333;background:#fdfdfd;}"
"    #filebrowser {width:100%; table-layout: fixed; border-collapse: collapse; margin-top: 1.5em; box-shadow: 0 1px 3px rgba(0,0,0,0.1); border-radius: 4px; overflow: hidden;}"
"    #filebrowser th, #filebrowser td {padding: 10px 8px; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; vertical-align: middle; border-bottom: 1px solid #eee;}"
"    #filebrowser th {background:#f1f1f1; color: #333; font-weight: bold; border-bottom: 2px solid #ddd; text-align:left;}"
"    #filebrowser tr:hover {background:#f9f9f9;}"
"    #filebrowser th.c-cb   {width: 5%; text-align: center;}"
"    #filebrowser th.c-name {width: 45%;}"
"    #filebrowser th.c-date {width: 20%;}"
"    #filebrowser th.c-size {width: 15%;}"
"    #filebrowser th.c-act  {width: 15%;}"
"    .disabled {pointer-events:none;opacity: 0.7;background:#EEE;}"
"    .flex-hdr {display: flex; justify-content: space-between; align-items: center; padding-bottom: 0.5em; border-bottom: 2px solid #ccc; margin-bottom: 1.5em;}"
"    "
"    /* Красивая зона Drag & Drop в черно-серых тонах */"
"    #drop-zone {"
"        border: 2px dashed #666;"
"        padding: 25px;"
"        text-align: center;"
"        background: #e8e8e8;"
"        margin: 20px 0;"
"        border-radius: 6px;"
"        display: flex;"
"        flex-direction: column;"
"        align-items: center;"
"        justify-content: center;"
"        transition: background 0.2s, border-color 0.2s;"
"    }"
"    #drop-zone.drag-over {"
"        background: #d0d0d0;"
"        border-color: #444;"
"    }"
"    "
"    /* Кнопки в черно-серых тонах */"
"    button, .btn-upload {"
"        background: #555;"
"        color: white;"
"        border: none;"
"        padding: 6px 12px;"
"        border-radius: 4px;"
"        cursor: pointer;"
"        font-family: monospace;"
"        font-size: 1em;"
"        margin: 0 4px;"
"        display: inline-block;"
"        transition: background 0.1s;"
"    }"
"    button:hover, .btn-upload:hover { background: #333; }"
"    .btn-del-sel { background: #666; display: none; }"
"    .btn-del-sel:hover { background: #444; }"
"    "
"    /* Футер */"
"    .footer {"
"        margin-top: 30px;"
"        padding-top: 15px;"
"        border-top: 1px solid #ccc;"
"        text-align: center;"
"        color: #666;"
"        font-size: 0.9em;"
"    }"
"</style>"
"</head>"
"<body>"
"    <div class='flex-hdr'>"
"        <h1 style='margin:0;'>Web Interface</h1>"
"        <span id='storage_info' style='font-size: 1.1em; color: #444; background: #eee; padding: 4px 8px; border-radius: 4px;'></span>"
"    </div>"
""
"    <!-- Drag & Drop -->"
"    <div id='drop-zone'>"
"        <span style='font-size: 1.2em; font-weight: bold; color: #444; margin-bottom: 5px;'>Drag & Drop files here to upload</span>"
"        <span style='font-size: 0.85em; color: #666; margin-bottom: 15px;'>or use the buttons below</span>"
"        "
"        <div>"
"            <button onclick='update_view(current_path)'>Refresh</button>"
"            <button onclick='create_folder()'>New folder</button>"
"            <button id='btn-delete-selected' class='btn-del-sel' onclick='delete_selected()'>Delete Selected</button>"
"            <label style='cursor: pointer; display: inline-block;'>"
"                <input style='display: none;' type='file' id='upload' multiple='multiple' onchange='add_files_to_queue(this.files)'>"
"                <span class='btn-upload'>Upload files</span>"
"            </label>"
"        </div>"
"        "
"        <div id='status' style='margin-top: 15px; font-weight: bold; color: #444; min-height: 1.2em;'></div>"
"    </div>"
""
"    <!-- Текущий путь в файловой системе -->"
"    <div style='margin: 20px 0 10px 0; font-size: 1.2em; font-weight: bold; border-bottom: 2px solid #ccc; padding-bottom: 5px;'>"
"        Path: <span id='subtitle' style='color: #444;'>/sd</span>"
"    </div>"
""
"    <div>"
"        <table id='filebrowser'>"
"            <thead>"
"               <tr>"
"                   <th class='c-cb'><input type='checkbox' id='select_all' onchange='toggle_select_all(this)'></th>"
"                   <th class='c-name'>Filename</th>"
"                   <th class='c-date'>Date Modified</th>"
"                   <th class='c-size'>Size</th>"
"                   <th class='c-act'>Action</th>"
"               </tr>"
"            </thead>"
"            <tbody></tbody>"
"        </table>"
"    </div>"
"    "
"    <!-- Футер с информацией об авторе -->"
"    <div class='footer'>"
"        <p>Ivan Svarkovsky, 2026</p>"
"        <p>Contact: <a href='mailto:ivansvarkovsky@gmail.com' style='color: #555;'>ivansvarkovsky@gmail.com</a></p>"
"    </div>"
"    "
"    <script>"
"        var current_path = '';"
"        var free_space_bytes = 0;"
"        var upload_queue = [];"
"        var uploading = false;"
"        var dragCounter = 0;"
""
"        function $(selector) {"
"            return document.querySelector(selector);"
"        }"
"        function basename(path) {"
"            return path.match('(.*)\\/(.*)')[2];"
"        }"
"        function dirname(path) {"
"            return path.match('(.*)\\/(.*)')[1];"
"        }"
"        function formatBytes(bytes, decimals) {"
"            if (decimals === undefined) decimals = 2;"
"            if (!+bytes) return '0 B';"
"            var k = 1024;"
"            var dm = decimals < 0 ? 0 : decimals;"
"            var sizes = ['B', 'KB', 'MB', 'GB', 'TB'];"
"            var i = Math.floor(Math.log(bytes) / Math.log(k));"
"            return parseFloat((bytes / Math.pow(k, i)).toFixed(dm)) + ' ' + sizes[i];"
"        }"
"        function api_req(cmd, arg1, arg2, callback, type) {"
"            var xhr = new XMLHttpRequest();"
"            xhr.responseType = type || 'json';"
"            xhr.addEventListener('loadstart', function() {"
"                $('#filebrowser').classList.add('disabled');"
"            });"
"            xhr.addEventListener('loadend', function() {"
"                $('#filebrowser').classList.remove('disabled');"
"            });"
"            xhr.addEventListener('load', callback);"
"            xhr.open('POST', '/api');"
"            xhr.send(JSON.stringify({ cmd: cmd, arg1: arg1, arg2: arg2 }));"
"        }"
"        function delete_file(path) {"
"            if (confirm('Delete ' + basename(path) + ' ?')) {"
"                api_req('delete', path, null, function () {"
"                    update_view(dirname(path));"
"                });"
"            }"
"        }"
"        function rename_file(path) {"
"            var new_path = prompt('New name for ' + basename(path), basename(path));"
"            if (new_path) {"
"                var full_new_path = dirname(path) + '/' + new_path;"
"                api_req('rename', path, full_new_path, function () {"
"                    update_view(dirname(path));"
"                });"
"            }"
"        }"
"        function create_folder() {"
"            var new_folder = prompt('New folder name', 'new folder');"
"            if (new_folder) {"
"                api_req('mkdir', current_path + '/' + new_folder, '', function () {"
"                    update_view(current_path);"
"                });"
"            }"
"        }"
"        function download_file(path) {"
"            window.open(path, '_blank').focus();"
"        }"
""
"        /* ─── Очередь последовательной загрузки + Проверка места ─── */"
"        function add_files_to_queue(files) {"
"            var total_size = 0;"
"            for (var i = 0; i < files.length; i++) {"
"                total_size += files[i].size;"
"            }"
"            "
"            if (total_size > free_space_bytes) {"
"                alert('Error: Not enough free space on SD card!\\nRequired: ' + formatBytes(total_size) + '\\nAvailable: ' + formatBytes(free_space_bytes));"
"                $('#upload').value = '';"
"                return;"
"            }"
"            "
"            for (var i = 0; i < files.length; i++) {"
"                upload_queue.push(files[i]);"
"            }"
"            "
"            if (!uploading) {"
"                process_upload_queue();"
"            }"
"        }"
""
"        function process_upload_queue() {"
"            if (upload_queue.length === 0) {"
"                uploading = false;"
"                $('#status').innerText = 'Upload completed!';"
"                setTimeout(function() { $('#status').innerText = ''; }, 3000);"
"                update_view(current_path);"
"                return;"
"            }"
"            "
"            uploading = true;"
"            var file = upload_queue.shift();"
"            var xhr = new XMLHttpRequest();"
"            "
"            xhr.addEventListener('loadstart', function() {"
"                $('#filebrowser').classList.add('disabled');"
"            });"
"            xhr.addEventListener('load', function () {"
"                free_space_bytes -= file.size;"
"                process_upload_queue();"
"            });"
"            xhr.addEventListener('error', function () {"
"                alert('Uploading ' + file.name + ' failed!');"
"                process_upload_queue();"
"            });"
"            xhr.upload.addEventListener('progress', function (e) {"
"                var pct = Math.floor(e.loaded/e.total * 100);"
"                $('#status').innerHTML = 'Uploading: <b>' + file.name + '</b> (' + pct + '%) [Remaining: ' + upload_queue.length + ']';"
"            });"
"            "
"            xhr.open('PUT', current_path + '/' + file.name);"
"            xhr.send(file);"
"        }"
""
"        /* ─── Массовое удаление файлов ─── */"
"        function toggle_select_all(master) {"
"            var checkboxes = document.querySelectorAll('.file-select');"
"            for (var i = 0; i < checkboxes.length; i++) {"
"                checkboxes[i].checked = master.checked;"
"            }"
"            update_delete_button_visibility();"
"        }"
""
"        function update_delete_button_visibility() {"
"            var selected = document.querySelectorAll('.file-select:checked');"
"            var btn = $('#btn-delete-selected');"
"            if (selected.length > 0) {"
"                btn.style.display = 'inline-block';"
"                btn.innerText = 'Delete Selected (' + selected.length + ')';"
"            } else {"
"                btn.style.display = 'none';"
"            }"
"        }"
""
"        function delete_selected() {"
"            var selected = document.querySelectorAll('.file-select:checked');"
"            if (selected.length === 0) return;"
"            "
"            var paths_to_delete = [];"
"            for (var i = 0; i < selected.length; i++) {"
"                paths_to_delete.push(selected[i].getAttribute('data-path'));"
"            }"
"            "
"            if (confirm('Are you sure you want to delete ' + paths_to_delete.length + ' selected files?')) {"
"                var total = paths_to_delete.length;"
"                "
"                function process_delete_queue() {"
"                    if (paths_to_delete.length === 0) {"
"                        $('#status').innerText = 'Deletion completed!';"
"                        setTimeout(function() { $('#status').innerText = ''; }, 3000); "
"                        $('#select_all').checked = false;"
"                        update_delete_button_visibility();"
"                        update_view(current_path);"
"                        return;"
"                    }"
"                    "
"                    var path = paths_to_delete.shift();"
"                    var current_num = total - paths_to_delete.length;"
"                    $('#status').innerText = 'Deleting: ' + basename(path) + ' (' + current_num + '/' + total + ')';"
"                    "
"                    api_req('delete', path, null, function() {"
"                        process_delete_queue();"
"                    });"
"                }"
"                process_delete_queue();"
"            }"
"        }"
""
"        /* ─── Обработчики Drag & Drop ─── */"
"        window.addEventListener('dragenter', function(e) {"
"            e.preventDefault();"
"            dragCounter++;"
"            if (dragCounter === 1) {"
"                document.body.classList.add('drag-over');"
"            }"
"        });"
"        window.addEventListener('dragleave', function(e) {"
"            e.preventDefault();"
"            dragCounter--;"
"            if (dragCounter === 0) {"
"                document.body.classList.remove('drag-over');"
"            }"
"        });"
"        window.addEventListener('dragover', function(e) {"
"            e.preventDefault();"
"        });"
"        window.addEventListener('drop', function(e) {"
"            e.preventDefault();"
"            dragCounter = 0;"
"            document.body.classList.remove('drag-over');"
"            if (e.dataTransfer.files.length > 0) {"
"                add_files_to_queue(e.dataTransfer.files);"
"            }"
"        });"
""
"        function update_view(path) {"
"            var btn = function (lbl, fn, arg) {"
"                return '<a href=\"#\" onclick=\"' + fn + '(\\'' + arg.replace(/'/g, '\\\\\\'') +  '\\')\">' + lbl + '</a>';"
"            };"
"            api_req('list', path, '', function () {"
"                var html = '<tr><td></td><td>' + btn('..', 'update_view', dirname(path)) + '</td><td></td><td></td><td></td></tr>';"
"                var files = this.response.files;"
"                var tot = this.response.total_bytes || 0;"
"                var fre = this.response.free_bytes || 0;"
"                free_space_bytes = fre;"
"                var usd = tot - fre;"
"                var pct = tot ? Math.round((usd / tot) * 100) : 0;"
"                "
"                $('#storage_info').innerHTML = 'Files: <b>' + files.length + '</b> &nbsp;|&nbsp; Space: <b>' + formatBytes(usd) + '</b> / <b>' + formatBytes(tot) + '</b> (' + pct + '%)';"
"                "
"                files.sort(function(a, b) { return a.name < b.name ? -1 : (a.name > b.name ? 1 : 0); });"
"                files.sort(function(a, b) { return a.is_dir > b.is_dir ? -1 : (a.is_dir < b.is_dir ? 1 : 0); });"
"                for (var i = 0; i < files.length; i++) {"
"                    var f = files[i];"
"                    f.path = path + '/' + f.name;"
"                    html += '<tr>';"
"                    html += '<td style=\"text-align:center;\"><input type=\"checkbox\" class=\"file-select\" data-path=\"' + f.path + '\" onchange=\"update_delete_button_visibility()\"></td>';"
"                    if (f.is_dir) {"
"                        html += '<td>' + btn(f.name + '/', 'update_view', f.path) + '</td>';"
"                        html += '<td>' + (new Date(f.mtime * 1000)).toLocaleString() + '</td>';"
"                        html += '<td>-</td>';"
"                    } else {"
"                        html += '<td>' + btn(f.name, 'download_file', f.path) + '</td>';"
"                        html += '<td>' + (new Date(f.mtime * 1000)).toLocaleString() + '</td>';"
"                        html += '<td>' + formatBytes(f.size) + '</td>';"
"                    }"
"                    html += '<td>' + btn('Rename', 'rename_file', f.path) + ' | ' + btn('Delete', 'delete_file', f.path) + '</td>';"
"                    html += '</tr>';"
"                }"
"                $('#filebrowser tbody').innerHTML = html;"
"                $('#subtitle').innerHTML = path;"
"                $('#status').innerText = '';"
"                current_path = path;"
"                update_delete_button_visibility();"
"            });"
"        }"
"        update_view('/sd');"
"    </script>"
"</body>"
"</html>"
};
